rule all:
    input:
        expand("output/{sample}/spaceranger_meanIntensity/filtered_feature_bc_matrix.h5", sample=glob_wildcards("input/{sample}/msi").sample)
        
rule perform_coreg:
    message:
        "Performing co-registration."
    conda: 'magpie'
    input:
        "input/{sample}/msi/MSI_metadata.csv"
    output:
        "output/{sample}/transformed.csv",
        "output/{sample}/transformed_withCoords.png",
        "output/{sample}/transformed.png"
    params:
        transform_type = 'TPS',
        sample = "{sample}"
    script:
        "scripts/alter_data.py"

rule make_spaceranger:
    message:
        "Creating spaceranger formatted output."
    conda: 'magpie_environment.yml'
    input:
        "output/{sample}/transformed.csv",
        "output/{sample}/transformed.png"
    output:
        "output/{sample}/spaceranger/filtered_feature_bc_matrix.h5"
    params:
        sample = "{sample}"
    script:
        "scripts/create_mock_spaceranger.py"

rule create_barcode_matrix:
    message:
        "Generating aggregated data."
    conda: 'magpie'
    input:
        "output/{sample}/spaceranger/filtered_feature_bc_matrix.h5"
    output:
        "output/{sample}/spaceranger_meanIntensity/filtered_feature_bc_matrix.h5"
    params:
        sample = "{sample}"
    script:
        "scripts/create_perbarcode_matrix.py"
