# Book settings
title: "Magpie Pipeline Documentation"
author: "Eleanor C. Williams"
logo: "figures/magpie_logo.png"
execute:
  execute_notebooks: "off"  # Disable automatic execution of notebooks during build
parse:
   myst_url_schemes: [mailto, http, https]
sphinx:
  config:
    html_show_copyright: false